### PR TITLE
Enable linting

### PR DESCRIPTION
**Pull request by sijis**
We are 1.0. Let's enable and enforce all linting checks.

### CODE REVIEW

**Comment by ndcampbell** [comment]
ugh, if you insist.

All these changes look good to me :)

**Comment by sijis** [comment]
We should do it early now, as the code is small and simple.
Enabling it later just makes it harder/difficult to do.

**Comment by sijis** [comment]
The good thing, is that going forward, you're tests will break and you'll know early on, it needs to be fixed.

**Comment by ndcampbell** [comment]
haha yeah, I agree.

**Pull request merged**
